OWNER_TYPE_DEFAULT = "default"
OWNER_ID_DEFAULT = "default"

LIST_TYPE_KEY_FOCUS = "key_focus"
LIST_TYPE_FOCUS = "focus"
LIST_TYPE_ARCHIVE_TARGETS = "archive_targets"

FREQ_NONE = "none"
FREQ_MINUTE = "minute"
FREQ_15MIN = "15min"
FREQ_DAILY = "daily"

ASSET_CATEGORY_STOCK = "stock"
ASSET_CATEGORY_MACRO = "macro"
ASSET_CATEGORY_TECH = "tech"
ASSET_CATEGORY_PRECIOUS_METAL = "precious_metal"
ASSET_CATEGORY_BASE_METAL = "base_metal"
ASSET_CATEGORY_ENERGY = "energy"
ASSET_CATEGORY_BLACK_CHAIN = "black_chain"
ASSET_CATEGORY_AGRI = "agri"
ASSET_CATEGORY_CHEMICALS = "chemicals"

ALLOWED_LIST_TYPES = {
    LIST_TYPE_KEY_FOCUS,
    LIST_TYPE_FOCUS,
    LIST_TYPE_ARCHIVE_TARGETS,
}
ALLOWED_FREQ = {FREQ_NONE, FREQ_MINUTE, FREQ_15MIN, FREQ_DAILY}
ALLOWED_ASSET_CATEGORIES = {
    ASSET_CATEGORY_STOCK,
    ASSET_CATEGORY_MACRO,
    ASSET_CATEGORY_TECH,
    ASSET_CATEGORY_PRECIOUS_METAL,
    ASSET_CATEGORY_BASE_METAL,
    ASSET_CATEGORY_ENERGY,
    ASSET_CATEGORY_BLACK_CHAIN,
    ASSET_CATEGORY_AGRI,
    ASSET_CATEGORY_CHEMICALS,
}
