OWNER_TYPE_DEFAULT = "default"
OWNER_ID_DEFAULT = "default"

LIST_TYPE_KEY_FOCUS = "key_focus"
LIST_TYPE_FOCUS = "focus"
LIST_TYPE_ARCHIVE_TARGETS = "archive_targets"

FREQ_NONE = "none"
FREQ_MINUTE = "minute"
FREQ_15MIN = "15min"
FREQ_DAILY = "daily"

ASSET_CATEGORY_STOCK = "stock"
ASSET_CATEGORY_MACRO = "macro"
ASSET_CATEGORY_FUTURES = "futures"
ASSET_CATEGORY_COMMODITY = "commodity"
ASSET_CATEGORY_PRECIOUS_METAL = "precious_metal"

ALLOWED_LIST_TYPES = {
    LIST_TYPE_KEY_FOCUS,
    LIST_TYPE_FOCUS,
    LIST_TYPE_ARCHIVE_TARGETS,
}
ALLOWED_FREQ = {FREQ_NONE, FREQ_MINUTE, FREQ_15MIN, FREQ_DAILY}
ALLOWED_ASSET_CATEGORIES = {
    ASSET_CATEGORY_STOCK,
    ASSET_CATEGORY_MACRO,
    ASSET_CATEGORY_FUTURES,
    ASSET_CATEGORY_COMMODITY,
    ASSET_CATEGORY_PRECIOUS_METAL,
}
